# Generated by Django 4.1.1 on 2022-09-30 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='connection',
            unique_together={('dest', 'dest_key')},
        ),
    ]
