# Generated by Django 4.1.1 on 2022-09-30 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0002_unique_conn_dest'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='pos_x',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='node',
            name='pos_y',
            field=models.FloatField(default=0),
        ),
    ]
